branches:
  only:
    - master
    - travis
    - pre-release
    - coverity_scan

git:
  depth: 1
  submodules: false

sudo: required

language: cpp

cache:
  directories:
    - $HOME/_cache

env:
  global:
    - secure: "bru1ZPjDOD4W+9tqwyEXB33FVJ5W0RcNjm7VHd37BKFMGFzwszN8g9SP5H8qJZJbHtxOVcBJjU9dafKckkS1/k7MINAgrAxeTZ3Ukp/+DxlFxU7YMf3AOAenMUB+QPGKasBCadCPvFkBSryY/7nd4T5etiQCDkXHJPQBRHpb0dPfaDCcvUpZQallMCKQ24zsgo8Jck23SxFBNy/5w/0/jLZFq0Rr5x9lQStDOjLCCx+6pPuXpYRFNbbThCsCvTqexSjiIElSPRbgJxjDsk6xrS9c9kCM60J8KpzFBQnweoQqqA9693NUQT9EmrlSmNkuJsGKpQXaF89CaRdt8c+KpZkZbic0i7DQCgtQws5tVKriwAOCpzWIruUNZzZnqc0WvlWuYjwng8TCFrJSoJHML/GIEGoYAWUFwW8/5rxRd0RKGaHd0Bs/ZaxOhGKu0jcfZVO4sCWNtSioqhNMUdRxj2zeG+y99oVTfdemXYFPoOfcFHV7J77N52WoEDPrMu2PlvoEBH8wFd999VEZGYpAWyeJMhZnbA+l+a6O2p9P2qfD6N6QoTXytwpnOQ8lZCFUZ8fOwKiEF+ESh06apJuUrC/8YlZCv7Dl2lvVAwQ/ueGwpXGAQdnXtP/PfPaEsr5FWUkxVzN1+q93Uk4Os3YcPlNbkBKwEixyrQ79easNHUU="

matrix:
  include:
    - name: "linux-gcc"
      os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - gem install coveralls-lcov
      before_script:
        - mkdir -p $TRAVIS_BUILD_DIR/build 
        - source $TRAVIS_BUILD_DIR/scripts/travis/clean-coverage.sh $TRAVIS_BUILD_DIR/build 
      after_success:
        - source $TRAVIS_BUILD_DIR/scripts/travis/submit-coverage.sh $TRAVIS_BUILD_DIR/build 

    - name: "linux-clang"
      os: linux
      dist: xenial
      compiler: clang
      before_install:
        - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

    - name: "gcc49"
      os: linux
      dist: xenial
      addons:
        apt: 
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - flex
            - bison
            - libboost-all-dev
            - z3
            - libz3-dev
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_install:
        - eval "${MATRIX_EVAL}"

    - name: "osx"
      os: osx
      #before_install:
        #- brew install bison
        #- export PATH="/usr/local/opt/bison/bin:$PATH"
        #- export LDFLAGS="-L/usr/local/opt/bison/lib"
      install:
        - export BISON_CACHED="$(find $HOME/_cache -name bison | grep -c "bison")"
        - if [ $BISON_CACHED == "0" ] ; then mkdir -p $HOME/_cache/bison ; fi 
        - if [ $BISON_CACHED == "0" ] ; then wget http://ftp.gnu.org/gnu/bison/bison-3.2.4.tar.gz ; fi 
        - if [ $BISON_CACHED == "0" ] ; then tar zxvf bison-3.2.4.tar.gz -C $HOME/_cache/bison --strip-components 1 ; fi 
        - cd $HOME/_cache/bison
        - if [ $BISON_CACHED == "0" ] ; then ./configure ; fi
        - if [ $BISON_CACHED == "0" ] ; then make ; fi
        - sudo make install

    - name: "coverity"
      os: linux
      dist: xenial
      compiler: gcc
      before_install: echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: "Bo-Yuan-Huang/ILAng"
            description: "A modeling and verification platform for SoCs using ILA"
          build_command_prepend: mkdir -p build; cd build; cmake ..
          build_command: make
          branch_pattern: coverity_scan

addons:
  apt:
    update: true
    packages:
      - lcov
      - flex
      - bison
      - libboost-all-dev
      - z3
      - libz3-dev
  homebrew:
    update: true
    packages:
      - flex
      - python
      - boost
      - boost-python
      - z3

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build
  - cd build
  - cmake .. -DILANG_BUILD_COV=ON -DCMAKE_BUILD_TYPE=Debug
  - make -j$(nproc)
  - sudo make install
  - make run_test
  - ctest -R ExampleCMakeBuild

notifications:
    email: false
